spring:
  profiles:
    active: dev
cloud:
  aws:
    stack:
      auto: false
server:
  servlet:
    context-path: /backend-for-frontend
service:
  dns: http://internal-ma-funadab-elb-private-845327145.ap-northeast-1.elb.amazonaws.com